.TH SPACE-NERDS-IN-SPACE "1" "SEPTEMBER 2018" "generate_skybox" "Games"
.SH NAME
generate_skybox \- generate skybox images suitable for use with Space Nerds In Space
.SH SYNOPSIS
.B generate_skybox

.SH DESCRIPTION
.\" Add any additional description here
.PP
generate_skybox makes six images for a skybox suitable for use with Space Nerds In Space.
.SH OPTIONS
.TP
\fB\-x, --xxxxx\fR
This is not really an option, this is just a template for the man
page for when the real options get implemented.
.SH EXAMPLE
.TP
.B generate_nebula
.SH NOTES
This program is still a work in progress and does not actually work
yet.
.SH AUTHOR
Written by Stephen M. Cameron
.br
