#!/bin/sh

# stop any existing processes first
./killem.sh
sleep 0.25

uname -a | grep '^Darwin ' > /dev/null 2>&1
if [ "$?" = "0" ]
then
	OSX="1"	
else
	OSX=0
fi

usage()
{
	echo "usage: quickstart star-ship-name password" 1>&2
	echo "example:" 1>&2
	echo "./quickstart Enterprise tribbles" 1>&2
	exit 1
}

shipname="$1"
if [ "$1" = "" ]
then
	shipname="spacenerd"	
fi

password="$2"
if [ "$2" = "" ]
then
	password="spacenerd"
fi

# start the lobby server
ssgl/ssgl_server

sleep 0.25

./snis_server localhost SPACENERDS `hostname` localhost --enable-enscript &

sleep 0.25

# start the game client and server in quickstart mode
if [ "$OSX" = "1" ]
then
	# do not use fullscreen on mac OSX (why?)
	./snis_client --quickstart --starship "$shipname" --pw "$password"
else
	./snis_client --fullscreen --quickstart --starship "$shipname" --pw "$password"
fi

exit $?

