#!/bin/sh

usage()
{
	echo "usage: quickjoin star-ship-name password" 1>&2
	echo "example:" 1>&2
	echo "./quickjoin Enterprise tribbles" 1>&2
	exit 1
}

shipname="$1"
if [ "$1" = "" ]
then
	shipname="spacenerd"	
fi

password="$2"
if [ "$2" = "" ]
then
	password="spacenerd"
fi

# check if lobby server is running
ps aux | grep 'ssgl_server' | grep -v grep > /dev/null 2>&1
if [ "$?" != "0" ]
then
	echo "Starting lobby server"
	ssgl/ssgl_server
	sleep 0.25
else
	echo "lobby server already running."
fi

# check if SNIS server is running
ps aux | grep 'snis_server' | grep -v grep > /dev/null 2>&1
if [ "$?" != "0" ]
then
	echo "Starting SNIS server"
	./bin/snis_server localhost SPACENERDS `hostname` localhost --enable-enscript &
	sleep 0.25
else
	echo "SNIS server already running."
fi

# start the game client and server in quickstart mode
./bin/snis_client --fullscreen --quickstart --starship "$shipname" --pw "$password"

exit $?

