.TH SPACE-NERDS-IN-SPACE "6" "Jan 2014" "snis_server" "Games"
.SH NAME
snis_server \- Multi player cooperative star ship bridge simulator (server) 
.SH SYNOPSIS
.B snis_server gameinstance serverhost location
.SH DESCRIPTION
.\" Add any additional description here
.warn 511
.PP
snis_server is a server process for the game Space Nerds In Space, which is
a multiplayer starship bridge simulator.  The server process simulates the 
game universe and processes input data from client processes and sends outputs
to client processes.  The "gameinstance" parameter is used by the game lobby
process (ssgl_server) to distinguish one game instance from another running
on the same host (multiple snis_server processes may be run on the same host).
The gameinstance should be a short human readable string to uniquely identify
the game instance.  The serverhost is the hostname of the server hosting the
ssgl_server process.  The location is a human readable string giving some idea
of the location of the server, or some other descriptive information. 
.SH Options:
.TP
\fB\--version\fR
Print the program's version number and exit.
.SH FILES
.PP
/dev/input/js0, the joystick device node.
.PP
/dev/input/event5, the rumble effect device. 
.PP
/usr/share/snis/sounds/*.ogg contain the audio data used by the game.
.PP
.SH ENVIRONMENT VARIABLES
.PP
SNISRAND can be set to a random seed to affect universe generation
.PP
SNIS_ASSET_DIR can cause the program to use a different directory to read
various assets (models, sounds, etc.) from a different directory allowing
easy substitution of all art assets.   Default is to use share/snis.
.SH SEE ALSO
.PP
snis_client(6), ssgl_server(6) 
.SH GOOD LUCK
.PP
You'll need it.
.SH AUTHOR
Written by Stephen M. Cameron 
.br
