.TH SPACE-NERDS-IN-SPACE "6" "Nov 2012" "snis_client" "Games"
.SH NAME
snis_client \- Multi player cooperative star ship bridge simulator (client) 
.SH SYNOPSIS
.B snis_client serverhost shipname password [ OPTIONS ]
.SH DESCRIPTION
.\" Add any additional description here
.warn 511
.PP
snis_client is the client process for the game Space Nerds In Space, which is
a multiplayer starship bridge simulator.  The server process simulates the 
game universe and processes input data from client processes and sends outputs
to client processes.  The serverhost parameter is the hostname of the host
running the ssgl_server game lobby process.  The shipname parameter is the name
of the ship in the game universe to which the client should connect (if the ship
does not exist, one is created).  The password is the password for the ship in the
game (this is a insecure "password", transmitted in plaintext).  The first client
on a ship establishes a ship name and password, subsequent clients join the ship.
(Mistyping either the shipname or the password will result in a new ship being
created with the wrong name/password.)
.SH Options:
.TP
\fB\--main\fR
Request this client process support the MAIN SCREEN role.
.PP
\fB\--navigation\fR
Request this client process support the NAVIGATION role.
.PP
\fB\--science\fR
Request this client process support the SCIENCE role.
.PP
\fB\--weapons\fR
Request this client process support the WEAPONS role.
.PP
\fB\--debug\fR
Request this client process support the DEBUG role.
.PP
\fB\--soundserver\fR
Request this client process support the SOUNDSERVER role.
.PP
\fB\--comms\fR
Request this client process support the COMMS (communication) role.
.PP
\fB\--version\fR
Print the program's version number and exit.
.SH ENVIRONMENT VARIABLES
SNIS_ASSET_DIR if set controls the directory from which sounds and 3D models
are read.  By default, "share/snis" is used.
.SH FILES
.PP
$SNIS_ASSET_DIR/sounds/*.ogg, various audio files used by the game.
.PP
$SNIS_ASSET_DIR/models/*.stl, various 3D models used by the game.
.PP
/dev/input/js0, the joystick device node.
.PP
/dev/input/event5, the rumble effect device. 
.PP
~/.space-nerds-in-space/snis-keymap.txt, the keyboard remapping configuration file.
.TP
The format of the keyboard remapping file is as follows:
.br
.br
Lines beginning with a '#' are comments.
.br
.br
Key mappings are defined by lines of the form "map key action"
.br
.br
Valid actions are:
.br
.br
.DI
    none, down, up, left, right, torpedo, transform,
    fullscreen, thrust, quit, pause, reverse,
    mainscreen, navigation, weapons, science,
    damage, debug, demon, f8, f9, onscreen,
    viewmode, zoom, unzoom
.DI
.br
Valid keys are:  
.br
.br
a-z, A-Z, 0-9, and most printable characters.
Keypad numerals 0-9 may be specified as kp_0 through  kp_9,  and
function  keys  f1  through  f12 can be specified f1 through f12
(obviously).  In addition the following strings may be  used  to
specify the corresponding keys:
.br
.br
.DI
       space       enter         return   backspace    delete
       pause       scrolllock    escape   sysreq       left
       right       up            down     kp_home      kp_down
       kp_up       kp_left       kp_right kp_end       kp_delete
       kp_insert   home          down     end          delete
       insert
.DE

.PP
/usr/share/snis/sounds/*.ogg contain the audio data used by the game.
.PP
.SH SEE ALSO
snis_server(6), ssgl_server(6)
.SH GOOD LUCK
.PP
You'll need it.
.SH AUTHOR
Written by Stephen M. Cameron 
.br
