#ifndef SNIS_MULTIVERSE_H__
#define SNIS_MULTIVERSE_H__

#define SNIS_MULTIVERSE_VERSION "SNISMULTIVERSE0001"

#define SNISMV_OPCODE_LOOKUP_BRIDGE 0x01
#define SNISMV_OPCODE_UPDATE_BRIDGE 0x02

#endif
