#!/bin/sh

if [ "$(id -u)" = "0" ]
then
	echo "You are root. Do not run this script as root." 1>&2
	exit 1
fi

# Hack this in for now
PREFIX=./

BINDIR=${PREFIX}/bin
if [ "$SNIS_ASSET_DIR" = "" ]
then
	export SNIS_ASSET_DIR=${PREFIX}/share/snis
fi
SNIS_SERVER=${BINDIR}/snis_server
SNIS_CLIENT=${BINDIR}/snis_client
SNIS_LIMITED_CLIENT=${BINDIR}/snis_limited_client
SNIS_MULTIVERSE=${BINDIR}/snis_multiverse
SSGL_SERVER=${BINDIR}/ssgl_server
LSSSGL=${BINDIR}/lsssgl
ASPECT_RATIO="${ASPECT_RATIO:-}"
LOBBYHOST=localhost
# ASPECT_RATIO="5:4"
# ASPECT_RATIO="4:3"
# ASPECT_RATIO="16:10"
# ASPECT_RATIO="16:9"

ENABLE_ENSCRIPT=
# ENABLE_ENSCRIPT=--enable-enscript

if [ "$ASPECT_RATIO" != "" ]
then
	ASPECT_RATIO_ARG="--aspect-ratio $ASPECT_RATIO"
else
	ASPECT_RATIO_ARG=""
fi

SOLARSYSTEM_NAME="default"

remove_snis_lock_dirs()
{
	for x in /tmp/snis_lock_dir.*
	do
		if [ -d "$x" ]
		then
			rmdir "$x"
		fi
	done
}

print_main_menu()
{
cat << EOF 1>&2

   1. Launch SNIS lobby server
	The lobby server allows clients to find servers
	There should be one lobby server total.
   2. Launch SNIS multiverse server
	The multiverse server stores player ship data
	There should be one multiverse server total
   3. Launch SNIS server
	There should be one snis server per solarsystem.
	There should be at least one instance of snis_server.
   4. Launch SNIS client process
	There should be one snis client process per player
	plus one more per ship for the main screen.
   5. Launch limited SNIS client process (no Open GL required).
   6. Stop all SNIS processes
   7. Stop all SNIS clients
   8. Stop all SNIS servers
   9. Check for asset updates
   10. Enter Lobby Host IP addr (currently $LOBBYHOST)
   0. Quit
EOF
}

kill_processes()
{
	pattern="$1"
	p=$(ps aux | egrep "$pattern" | grep -v 'grep')
	if [ "$p" = "" ]
	then
		echo "There are no processes to kill."
		return
	else
		echo "$p"
	fi
	ps aux | egrep "$pattern" | grep -v 'grep' | awk '{ printf("kill %s\n", $2); }' | /bin/sh
	echo "Killed the above processes."
}

start_snis_lobby()
{
	if [ "${LOBBYHOST}" != "localhost" ]
	then
		echo
		echo "WARNING: current lobby host is ${LOBBYHOST}, not localhost."
		echo "Are you sure you mean to start a local lobby server (y/n)?"
		read x
		if [ "$x" != "y" ]
		then
			echo "Not starting lobby host."
			return
		else
			echo "Starting local lobby host anyway."
		fi
	fi
	echo
	echo "Starting the lobby server"
	echo
	${SSGL_SERVER} > snis_lobby_log.txt 2>&1
	sleep 0.25
}

start_snis_multiverse()
{
	local autowrangle=
	local exempt=
	echo -n "Autowrangle snis_servers (y/n, default = y)?"
	read x
	if [ "$x" != "n" ]
	then
		echo
		echo "Which solarsystem should be exempted from auto-wrangling?"
		get_solarsystem_name
		exempt="-e $SOLARSYSTEM_NAME"
		autowrangle=-a
		echo "Exempting solarsystem $SOLARSYSTEM_NAME from auto-wrangling."
	else
		autowrangle=
		exempt=
	fi

	if [ ! -d ./snisdb ]
	then
		echo "./snisdb/ does not exist, creating directory." 1>&2
		mkdir ./snisdb
		if [ "$?" != "0" ]
		then
			echo "mkdir ./snisdb failed."
		fi
		if [ ! -d ./snisdb ]
		then
			echo "Directory ./snisdb does not exist, snis_multiverse will not run without it, please create it." 1>&2
			echo "Failed to start multiverse server" 1>&2
			return;
		fi
		echo "Created ./snisdb for snis_multiverse" 1>&2
	fi
	(${SNIS_MULTIVERSE} $autowrangle -l "${LOBBYHOST}" -n nickname -L narnia $exempt > snis_multiverse_log.txt 2>&1 ; \
		echo "snis_multiverse died, status was $?" 1>&2 ) &
}

get_solarsystem_name()
{
	while [ "1" = "1" ]
	do
		default="$SOLARSYSTEM_NAME"
		dname="."

		echo "Choose a solar system:"
		for ss in ${SNIS_ASSET_DIR}/solarsystems/*/assets.txt
		do
			dname=$(dirname "$ss")
			name=$(basename "$dname")
			echo "   $name"
		done
		echo -n "Enter the name of the solarsystem (default = $default): "
		read ssname;
		if [ "$ssname" = "" ]
		then
			ssname="$default"
		fi
		if [ ! -f "${SNIS_ASSET_DIR}/solarsystems"/"$ssname"/assets.txt ]
		then
			echo "Invalid choice: $ssname"
		else
			break;
		fi
	done
	if [ -d ${SNIS_ASSET_DIR}/solarsystems/"$ssname" -a -f ${SNIS_ASSET_DIR}/solarsystems/"$ssname"/assets.txt ]
	then
		SOLARSYSTEM_NAME="$ssname"
	else
		SOLARSYSTEM_NAME="default"
	fi
}

uppercase()
{
	echo "$1" | tr '[a-z]' '[A-Z]'
}

start_snis_server()
{
	echo
	echo "Starting snis_server"
	echo
	get_solarsystem_name
	echo "Using solar system $SOLARSYSTEM_NAME"
	SS1="$SOLARSYSTEM_NAME"
	${SNIS_SERVER} -l "${LOBBYHOST}" -L $(uppercase "$SS1") -m narnia -s "$SS1" ${ENABLE_ENSCRIPT} > snis_server_log.txt 2>&1 &
	sleep 2.5
}

start_snis_client()
{
	echo
	echo "Starting snis_client"
	echo
	CLIENT="$1"
	${CLIENT} --lobbyhost "${LOBBYHOST}" $ASPECT_RATIO_ARG --fullscreen > snis_client_log.txt 2>&1 &
	sleep 1
	# --starship "$shipname" --pw "$password" $@
}

enter_lobby_host()
{
	echo -n "Enter lobby host: "
	read x
	export LOBBYHOST="$x"
}

reformat_processes()
{
	awk ' \
		/ssgl_server/ { printf("%20s -- %s\n", "LOBBY SERVER", $0); next; } \
		/snis_client/ { printf("%20s -- %s\n", "SNIS CLIENT", $0); next; } \
		/snis_server/ { printf("%20s -- %s\n", "SNIS SERVER", $0); next; } \
		/snis_multiverse/ { printf("%20s -- %s\n", "MULTIVERSE SERVER", $0); next; } \
		{ printf("%20s -- %s\n", "UNKNOWN", $0); next; }'
}

show_snis_processes()
{
	echo "------------------------------------------------------------"
	p=$(ps aux | egrep 'snis_multiverse|snis_server|snis_client|ssgl_server' | grep -v grep)
	if [ "$p" = "" ]
	then
		echo "No SNIS processes are currently running."
	else
		echo "The following SNIS processes are running:"
		echo "$p" | reformat_processes
	fi
	echo "------------------------------------------------------------"
}

check_for_bad_lockfiles()
{
	for x in /tmp/snis_server_lock.*
	do
		if [ ! -d "$x" ]
		then
			continue;
		fi
		instancename=$(echo "$x" | sed -e 's/.*[.]//')
		ps aux | grep snis_server | grep "[-]L $instancename[ ]" > /dev/null 2>&1
		if [ "$?" = "1" ]
		then
			echo 1>&2
			echo "WARNING: lockdir $x found, but no corresponding snis_server process!" 1>&2
			echo "You may need to execute the following command: rmdir $x" 1>&2
			echo 1>&2
		fi
	done
}

check_for_ip_address()
{
	ipaddr=$(${SSGL_SERVER} --find-ip-address 2>/dev/null)
	if [ "$ipaddr" = "" -o "$ipaddr" = "0.0.0.0" ]
	then
		echo "Failed to find primary IP address." 1>&2
		echo "You might need to set SSGL_PRIMARY_IP_PROBE_ADDR" 1>&2
		echo "If you are on a LAN with an IP address like 192.168.1.10" 1>&2
		echo "try 'export SSGL_PRIMARY_IP_PROBE_ADDR=192.168.1.10'" 1>&2
		exit 1
	fi
}

check_for_ip_address

while [ "1" = "1" ]
do
	echo
	echo "     Welcome to Space Nerds In Space"
	echo
	show_snis_processes
	print_main_menu
	check_for_bad_lockfiles
	echo -n "   Choose [0-7]: "
	read x

	case "$x" in
	0)
	   echo
	   echo "Goodbye! Thanks for playing!"
	   echo
	   exit
		;;
	6) kill_processes 'snis_server|snis_client|snis_limited_client|snis_multiverse|ssgl_server'
		remove_snis_lock_dirs
		;;
	7) kill_processes 'snis_client|snis_limited_client'
		;;
	8) kill_processes 'snis_server|snis_multiverse|ssgl_server'
		remove_snis_lock_dirs
		;;
	1) start_snis_lobby
		;;
	2) start_snis_multiverse
		;;
	3) start_snis_server
		;;
	4) start_snis_client "$SNIS_CLIENT"
		;;
	5) start_snis_client "$SNIS_LIMITED_CLIENT"
		;;
	9) util/snis_update_assets.sh --dry-run
		;;
	10) enter_lobby_host
		;;
	*) echo "Invalid choice."
	        ;;
	esac
done

exit

