.TH SPACE-NERDS-IN-SPACE "6" "JUNE 2016" "snis_client" "Games"
.SH NAME
snis_client \- Multi player cooperative star ship bridge simulator (client) 
.SH SYNOPSIS
.B snis_client serverhost shipname password [ OPTIONS ]
.SH DESCRIPTION
.\" Add any additional description here
.warn 511
.PP
snis_client is the client process for the game Space Nerds In Space, which is
a multiplayer starship bridge simulator.  The server process simulates the 
game universe and processes input data from client processes and sends outputs
to client processes.  The serverhost parameter is the hostname of the host
running the ssgl_server game lobby process.  The shipname parameter is the name
of the ship in the game universe to which the client should connect (if the ship
does not exist, one is created).  The password is the password for the ship in the
game (this is a insecure "password", transmitted in plaintext).  The first client
on a ship establishes a ship name and password, subsequent clients join the ship.
(Mistyping either the shipname or the password will result in a new ship being
created with the wrong name/password.)
.SH Options:
.TP
\fB-r x:y, --aspect-ratio x:y\fR
Specify a requested aspect ratio.  By default, the window manager is queried
to determine the display dimensions, and the aspect ratio is made to match.
Other arbitrary aspect ratios may be specified.  This may be desirable if
you have a display that is significantly different from the display the game
was designed on (16:9).  Common aspect ratios (circa 2015) are 5:4, 4:3, 16:10
and 16:9 (according to wikipedia). The values specified for x and y must be
integers greater than zero and must be separatedy by a comma or a colon.  Specifying
and aspect ratio will disable the --fullscreen option.  Note: You may experience
some problems with widget and text placement with aspect ratios significantly
different than 16:9.
.TP
\fB\-C, --comms\fR
Request this client process support the COMMS (communication) role.
.TP
\fB\--debug\fR
Request this client process support the DEBUG role.
.TP
\fB\-f, --fullscreen\fR
Use the full display, with no window borders.  This option is ignored
if the --aspect-ratio option is also specified.
.TP
\fB\-M, --main\fR
Request this client process support the MAIN SCREEN role.
.TP
\fB\-m, --monitor m\fR
If your system has multiple monitors, the --monitor option allows you to
specify which one you want to use.  It takes an integer argument, with 0
being the first monitor, 1 being the second, etc.  The default monitor may
be designated by -1 (or by omitting the --monitor option entirely).
.TP
\fB\-N, --navigation\fR
Request this client process support the NAVIGATION role.
.TP
\fB\-L, --nolobby\fR
Do not use the lobby server.  This option requires that the
--serverport and --serverhost options be used and that the --lobbyhost
option is not used.
.TP
\fB\-S, --science\fR
Request this client process support the SCIENCE role.
.TP
\fB\-s host, --serverhost host\fR
Specify the hostname of the server to contact.  This option requires
the --nolobby and --serverport options are also used, and requires that
the --lobbyhost option is not used.
.TP
\fB\-p portnumber, --serverport portnumber\fR
Specify the portnumber of the snis_server process.  This option requires
the --nolobby and --serverhost options are also used, and requires that
the --lobbyhost option is not used.
.TP
\fB\-* solarsystem, --solarsystem solarsystem\fR
Load the specified solarsystem assets instead of the default assets.  These
are defined by $SNIS_ASSET_DIR/solarsystems/*/assets.txt
.TP
\fB\-a, --soundserver\fR
Request this client process support the SOUNDSERVER role.
.TP
\fB\-W, --weapons\fR
Request this client process support the WEAPONS role.
.TP
\fB\-v, --version\fR
Print the program's version number and exit.
.SH ENVIRONMENT VARIABLES
SNIS_ASSET_DIR if set controls the directory from which sounds and 3D models
are read.  By default, "share/snis" is used.
.PP
SNIS_COLORS if set, the file $SNIS_ASSET_DIR/$SNIS_COLORS is read to obtain
color information instead of reading the default file of $SNIS_ASSET_DIR/user_colors.cfg
.PP
SNIS_SUPPRESS_RENDER_TO_TEXTURE if set, suppresses the use of OpenGL's render to texture
feature even if the driver claims to support it.
.PP
SNIS_SUPPRESS_MSAA if set, suppresses the use of OpenGL's MSAA
feature even if the driver claims to support it.
.PP
SNIS_SUPPRESS_RENDER_TO_FBO if set, suppresses the use of OpenGL's render to fbo
feature even if the driver claims to support it.
.PP
SNIS_AUDIO_DEVICE if set, manually selects an audio device. Ordinarily a default
device is chosen.  This variable allows the default device to be overridden.  This
value should be an integer between 0 and the number of sound devices you have minus
one.  You can see which audio devices you have by running "aplay -l", or
"pactl list".  Note: Text-to-Speech functionality (e.g. "the computer" within the
game) will not honor SNIS_AUDIO_DEVICE as text to speech is implemented by an
external program (either pico2wave (plus play or aplay) or espeak) which figures
out which sound device to use on its own.
.PP
.SH FILES
.PP
$SNIS_ASSET_DIR/sounds/*.ogg, various audio files used by the game.
.PP
$SNIS_ASSET_DIR/models/*.stl, various 3D models used by the game.
.PP
$SNIS_ASSET_DIR/solarsystems/*/assets.txt, per-solarsystem art assets.
.PP
/dev/input/js0, the joystick device node.
.PP
/dev/input/event5, the rumble effect device. 
.PP
/tmp/snis-natural-language-fifo, a named pipe which the client reads from.  Anything sent into this
pipe is forwarded to snis_server as a natural language request.  This is useful for sending the output
of a speech recognition system to snis_server.
.PP
~/.space-nerds-in-space/snis-keymap.txt, the keyboard remapping configuration file.
.TP
The format of the keyboard remapping file is as follows:
.br
.br
Lines beginning with a '#' are comments.
.br
.br
Key mappings are defined by lines of the form "map key action"
.br
.br
Valid actions are:
.br
.br
.DI
    none, down, up, left, right, torpedo, transform,
    fullscreen, thrust, quit, pause, reverse,
    mainscreen, navigation, weapons, science,
    damage, debug, demon, f8, f9, f10, onscreen,
    viewmode, zoom, unzoom, phaser, rendermode,
    keyrollleft, keyrollright, keyschiball_yawleft,
    keysciball_yawright, keysciball_pitchup,
    keysciball_pitchdown, keysciball_rollright,
    keysciball_rollleft, key_invert_vertical,
    key_toggle_frame_stats, key_camera_mode, key_page_up,
    key_page_down, key_toggle_space_dust
.DI
.br
Valid keys are:  
.br
.br
a-z, A-Z, 0-9, and most printable characters.
Keypad numerals 0-9 may be specified as kp_0 through  kp_9,  and
function  keys  f1  through  f12 can be specified f1 through f12
(obviously).  In addition the following strings may be  used  to
specify the corresponding keys:
.br
.br
.DI
       space       enter         return   backspace    delete
       pause       scrolllock    escape   sysreq       left
       right       up            down     kp_home      kp_down
       kp_up       kp_left       kp_right kp_end       kp_delete
       kp_insert   home          down     end          delete
       insert
.DE

.PP
$SNIS_ASSET_DIR/user_colors.cfg allows customizing of the colors of nearlly all UI
elements.  The file contains comments describing its format. In brief, there are
three types of lines.  A comment is a line beginning with a '#' or containing only
whitespace, and is ignored.  A 'color' line begins with the word 'color', which is
followed by a user supplied name (eg: 'purple') then a space, then a color definition
which is a '#' followed by 2 hex digits for each of red, green and blue, so, for
example:
.br
.DI

color purple #ff00ff

.DE
.PP
Finally, lines to change the colors of ui-components are of the form:
.br
.DI

ui-component color

.DE
where 'ui-component' is a 'magic word' identifying one of the ui components
(see comments in $SNIS_ASSET_DIR/user_colors.cfg) and color is either a word
defined in a prior 'color' line, or else a color specification of the form
#rrggbb where r, g, and b are hex digits.  For example:
.br
.DI

nav-button purple
.br
nav-slider #00ff00

.DE
.PP
.SH SEE ALSO
snis_server(6), ssgl_server(6), snis_multiverse(6)
.SH GOOD LUCK
.PP
You'll need it.
.SH AUTHOR
Written by Stephen M. Cameron 
.br
