#ifndef SOUNDS_H
#define SOUNDS_H

#define MAX_CONCURRENT_SOUNDS 20
#define NSOUND_CLIPS 52
#define NHULL_CREAK_SOUNDS 10

#define EXPLOSION_SOUND 1
#define TORPEDO_LAUNCH_SOUND 2
#define LASER_FIRE_SOUND 3
#define DISTANT_TORPEDO_HIT_SOUND 2
#define TORPEDO_HIT_SOUND 2
#define DISTANT_PHASER_HIT_SOUND 2
#define PHASER_HIT_SOUND 2
#define ONSCREEN_SOUND 4
#define OFFSCREEN_SOUND 5
#define CHANGESCREEN_SOUND 6
#define SLIDER_SOUND 7
#define SCIENCE_DATA_ACQUIRED_SOUND 8
#define SCIENCE_PROBE_SOUND 9
#define TTY_CHATTER_SOUND 10 
#define WARPDRIVE_SOUND 11
#define TORPEDO_LOAD_SOUND 12
#define RED_ALERT_SOUND 13
#define STARSHIP_JOINED 14
#define CREWMEMBER_JOINED 15
#define HULL_BREACH_IMMINENT 16
#define FUEL_LEVELS_CRITICAL 17
#define INCOMING_FIRE_DETECTED 18
#define LASER_FAILURE 19
#define PROXIMITY_ALERT 20
#define SPACESHIP_CRASH 21
#define REVERSE_SOUND 22
#define COMMS_HAIL_SOUND 23
#define TRANSPORTER_SOUND 24
#define DANGEROUS_RADIATION 25
#define LEAVING_SECURE_AREA 26
#define ENTERING_SECURE_AREA 27
#define ROBOT_INSERT_COMPONENT 28
#define ROBOT_REMOVE_COMPONENT 29
#define WARP_DRIVE_FUMBLE 30
#define ATMOSPHERIC_FRICTION 31
#define DOCKING_SOUND 32
#define DOCKING_SYSTEM_DISENGAGED 33
#define DOCKING_SYSTEM_ENGAGED 34
#define PERMISSION_TO_DOCK_DENIED 35
#define PERMISSION_TO_DOCK_GRANTED 36
#define PERMISSION_TO_DOCK_EXPIRED 37
#define WELCOME_TO_STARBASE 38
#define MINING_BOT_DEPLOYED 39
#define MINING_BOT_STOWED 40 
#define MINING_BOT_STANDING_BY 41 
#define HULL_CREAK_0 42
#define HULL_CREAK_1 43
#define HULL_CREAK_2 44
#define HULL_CREAK_3 45
#define HULL_CREAK_4 46
#define HULL_CREAK_5 47
#define HULL_CREAK_6 48
#define HULL_CREAK_7 49
#define HULL_CREAK_8 50
#define HULL_CREAK_9 51

#endif
