#ifndef SOUNDS_H
#define SOUNDS_H

#define MAX_CONCURRENT_SOUNDS 20
#define NSOUND_CLIPS 9

#define EXPLOSION_SOUND 1
#define TORPEDO_LAUNCH_SOUND 2
#define LASER_FIRE_SOUND 3
#define DISTANT_TORPEDO_HIT_SOUND 2
#define TORPEDO_HIT_SOUND 2
#define DISTANT_PHASER_HIT_SOUND 2
#define PHASER_HIT_SOUND 2
#define ONSCREEN_SOUND 4
#define OFFSCREEN_SOUND 5
#define CHANGESCREEN_SOUND 6
#define SLIDER_SOUND 7
#define SCIENCE_DATA_ACQUIRED_SOUND 8

#endif
