.TH SUPER-SIMPLE-GAME-LOBBY "6" "Nov 2012" "ssgl_server" "Games"
.SH NAME
ssgl_server \- Super Simple Game Lobby server 
.SH SYNOPSIS
.B ssgl_server
.SH DESCRIPTION
.\" Add any additional description here
.warn 511
.PP
ssgl_server is the server process for a very simple game lobby service.
It listens for connections on tcp port 2419 (gamelobby) from game servers
and game clients and provides a mechanism for game clients to connect to
game servers and nothing more.  It requires a gamelobby entry in /etc/services
identifying the "gamelobby" service at tcp and udp port number 2419.
.DI
gamelobby	2419/tcp
gamelobby	2419/udp
.DE
.SH Options:
.TP
\fBnone\fR
.SH FILES
.PP
/etc/services -- to identify the gamelobby service port number
.PP
.SH SEE ALSO
snis_server(6), snis_client(6)
.SH GOOD LUCK
.PP
You'll need it.
.SH AUTHOR
Written by Stephen M. Cameron 
.br
